@echo off
setlocal EnableExtensions EnableDelayedExpansion

cd /d "%~dp0"

set "RECORDINGS=%CD%\recordings"
if not exist "%RECORDINGS%\" (
    echo ERROR: recordings folder not found: "%RECORDINGS%"
    pause
    exit /b 1
)

for /f "delims=" %%D in ('dir /b /ad /o-n "%RECORDINGS%" 2^>nul') do (
    if not defined LATEST set "LATEST=%RECORDINGS%\%%D"
)

if not defined LATEST (
    echo ERROR: no session folders found under "%RECORDINGS%"
    pause
    exit /b 1
)

where uv >nul 2>nul
if not errorlevel 1 (
    set "USE_UV=1"
) else if exist "%CD%\.venv\Scripts\python.exe" (
    set "PYTHON_EXE=%CD%\.venv\Scripts\python.exe"
) else (
    echo ERROR: could not find uv in PATH or project Python at ".venv\Scripts\python.exe"
    pause
    exit /b 1
)

echo Latest recording folder:
echo   "%LATEST%"
echo.

set "COUNT=0"
set "FAILED=0"

for /f "delims=" %%F in ('dir /b /a-d /on "%LATEST%\*.mp4" 2^>nul') do (
    set "BASE=%%~nF"
    set "FULL=%LATEST%\%%F"

    if /i "!BASE:~-7!"=="_inputs" (
        rem Skip files generated by this script.
    ) else if /i "!BASE:~-9!"=="._hud_tmp" (
        rem Skip temporary HUD files.
    ) else if exist "%LATEST%\!BASE!.jsonl" (
        set /a COUNT+=1
        echo [!COUNT!] Overlay inputs on:
        echo   "!FULL!"
        if defined USE_UV (
            uv run python scripts/overlay_inputs_on_video.py "!FULL!"
        ) else (
            "!PYTHON_EXE!" scripts\overlay_inputs_on_video.py "!FULL!"
        )
        if errorlevel 1 (
            echo ERROR: overlay failed for "!FULL!"
            set "FAILED=1"
        )
        echo.
    )
)

if "%COUNT%"=="0" (
    echo ERROR: no mp4 files with matching jsonl sidecars found in "%LATEST%"
    pause
    exit /b 1
)

if "%FAILED%"=="1" (
    echo Done with errors.
    pause
    exit /b 1
)

echo Done. Generated *_inputs.mp4 files in:
echo   "%LATEST%"
pause
